services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - '5432:5432'
  backend:
    build: ./apps/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todo_db
    ports:
      - '3000:3000'
  frontend:
    build: ./apps/frontend
    depends_on:
      - backend
    ports:
      - '5173:5173'